### PR TITLE
Inference with lower VRAM requirements

### PR DESCRIPTION
**Pull request by frutiemax92**
Inference with bfloat16 and float16 works on a RTX4070. Float32 gives OOM.

### CODE REVIEW

**Comment by nitinmukesh** [comment]
Thank you for this PR.

tested on 8GB VRAM

Before 
image
Inference time: 5-6M


After using your updates
image
Inference time: 2M

**Comment by lawrence-cj** [comment]
Thanks a lot for your work along the time

**Comment by FurkanGozukara** [comment]
this changed how batch size works

now it process 6 times if batch size is 6 and each iteration it becomes slower and slower

definitely something wrong

image

**Comment by lawrence-cj** [comment]
The batch inference is not changed by this PR. The only thing this PR change is adding some lines of torch.no_grad(). SanaPipeline class in the current repo only supports batch inference for the same prompt: https://github.com/NVlabs/Sana/blob/c66ebf9702542a2fd418727903a8735f7d9ec094/app/sana_pipeline.py#L195
If you input a prompts list, it will generate it separately.

**Comment by FurkanGozukara** [comment]
then it is probably because of the changes i had to make it to run on windows - i probably broken something because i am giving only 1 prompt via gradio

https://github.com/FurkanGozukara/Sana/blob/main/app/sana_pipeline.py

**Comment by FurkanGozukara** [comment]
> um_images_per_pro

your code has this for batch size

```
            for _ in range(num_images_per_prompt):
                with torch.no_grad():
                    prompts.append(
                        prepare_prompt_ar(prompt, self.base_ratios, device=self.device, show=False)[0].strip()
                    )
```

**Comment by lawrence-cj** [comment]
Yes. This is only for generating multiple images with a single prompt. If you want to batch inference with input like: ['car', 'car', 'car'], then it's not supported for now.

**Comment by frutiemax92** [comment]
> then it is probably because of the changes i had to make it to run on windows - i probably broken something because i am giving only 1 prompt via gradio
> 
> https://github.com/FurkanGozukara/Sana/blob/main/app/sana_pipeline.py

I am using WSL2 and the sample script from the model's page on github.

**Comment by yujincheng08** [comment]
This PR breaks batch inference. Fixed in https://github.com/NVlabs/Sana/commit/9da85500faaf052d08bd504756cbf2ee7ddefa89.

**Pull request merged**
